name: Android CI/CD

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  static-analysis:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Services JSON for Lint
        run: |
          printf "%s" "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

      # - name: Run Android Lint
      #   run: ./gradlew lintDebug

#  build:
#    name: Build APK
#    needs: static-analysis
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Decode Google Services JSON
#        env:
#          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
#        run: |
#          echo $GOOGLE_SERVICES_BASE64 | base64 --decode > app/google-services.json
#
#
#      - name: Build APK
#        run: ./gradlew assembleDebug
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: chatroom-debug-apk
#          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    name: Build & Deploy APK
    # needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_BASE64 | base64 --decode > app/google-services.json

      - name: Decode Keystore
        run: echo "${{ secrets.KEY_APK }}" | base64 --decode > app/release-key.jks

      - name: Build Release APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew :app:assembleRelease

      - name: List built files
        run: find app/build/outputs/apk/ -name "*.apk"

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: chatroom-release-apk
          path: app/build/outputs/apk/debug/app-release.apk
